# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 384e5c0ef6775d2a31cc28e85f43dd7f5e56e13c5a88a8f47087405eab15974655ae9246589ba6d401105f328e850f59f0b82eee33c3488a91e142c9ae0d5ed9

test:
  secret_key_base: d3144598e44f09598dd771a8d97474fb40c385c8ab60c1189a2e3d3ed97241a434c27380fddd16d0b76992e446f3d831659a92b0c994f32d5c679787423be622

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
